/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CsvFileService } from "../csvFile.service";
import { CsvFileCreateInput } from "./CsvFileCreateInput";
import { CsvFile } from "./CsvFile";
import { CsvFileFindManyArgs } from "./CsvFileFindManyArgs";
import { CsvFileWhereUniqueInput } from "./CsvFileWhereUniqueInput";
import { CsvFileUpdateInput } from "./CsvFileUpdateInput";
import { RecordFindManyArgs } from "../../record/base/RecordFindManyArgs";
import { Record } from "../../record/base/Record";
import { RecordWhereUniqueInput } from "../../record/base/RecordWhereUniqueInput";

export class CsvFileControllerBase {
  constructor(protected readonly service: CsvFileService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CsvFile })
  async createCsvFile(
    @common.Body() data: CsvFileCreateInput
  ): Promise<CsvFile> {
    return await this.service.createCsvFile({
      data: data,
      select: {
        createdAt: true,
        filePath: true,
        id: true,
        processed: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [CsvFile] })
  @ApiNestedQuery(CsvFileFindManyArgs)
  async csvFiles(@common.Req() request: Request): Promise<CsvFile[]> {
    const args = plainToClass(CsvFileFindManyArgs, request.query);
    return this.service.csvFiles({
      ...args,
      select: {
        createdAt: true,
        filePath: true,
        id: true,
        processed: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CsvFile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async csvFile(
    @common.Param() params: CsvFileWhereUniqueInput
  ): Promise<CsvFile | null> {
    const result = await this.service.csvFile({
      where: params,
      select: {
        createdAt: true,
        filePath: true,
        id: true,
        processed: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CsvFile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCsvFile(
    @common.Param() params: CsvFileWhereUniqueInput,
    @common.Body() data: CsvFileUpdateInput
  ): Promise<CsvFile | null> {
    try {
      return await this.service.updateCsvFile({
        where: params,
        data: data,
        select: {
          createdAt: true,
          filePath: true,
          id: true,
          processed: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CsvFile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCsvFile(
    @common.Param() params: CsvFileWhereUniqueInput
  ): Promise<CsvFile | null> {
    try {
      return await this.service.deleteCsvFile({
        where: params,
        select: {
          createdAt: true,
          filePath: true,
          id: true,
          processed: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/records")
  @ApiNestedQuery(RecordFindManyArgs)
  async findRecords(
    @common.Req() request: Request,
    @common.Param() params: CsvFileWhereUniqueInput
  ): Promise<Record[]> {
    const query = plainToClass(RecordFindManyArgs, request.query);
    const results = await this.service.findRecords(params.id, {
      ...query,
      select: {
        createdAt: true,

        csvFile: {
          select: {
            id: true,
          },
        },

        data: true,
        id: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/records")
  async connectRecords(
    @common.Param() params: CsvFileWhereUniqueInput,
    @common.Body() body: RecordWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      records: {
        connect: body,
      },
    };
    await this.service.updateCsvFile({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/records")
  async updateRecords(
    @common.Param() params: CsvFileWhereUniqueInput,
    @common.Body() body: RecordWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      records: {
        set: body,
      },
    };
    await this.service.updateCsvFile({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/records")
  async disconnectRecords(
    @common.Param() params: CsvFileWhereUniqueInput,
    @common.Body() body: RecordWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      records: {
        disconnect: body,
      },
    };
    await this.service.updateCsvFile({
      where: params,
      data,
      select: { id: true },
    });
  }
}
